# -*- coding: utf-8 -*-
"""Make Educational Youtube Videos Halal (remove music).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVzFppcTwwIfaPxMehNdiQvhrJ02oWrk
"""

# ==============================
# 1. Setup (Install needed tools)
# ==============================
!pip install yt-dlp ffmpeg-python demucs

# ==============================
# 2. Upload cookies.txt if authentication is required
# ==============================
from google.colab import files
print("Upload your cookies file from browser now (e.g. www.youtube.com_cookies.txt)")
uploaded = files.upload()
COOKIE_FILENAME = next((x for x in uploaded if x.endswith('.txt')), None)

# ==============================
# 3. Paste your YouTube Video URL here
# ==============================
VIDEO_URL = input("Paste your YouTube video URL here, then press Enter: ")
print(f"Your selected YouTube URL: {VIDEO_URL}")

# ==============================
# 4. Download audio and video using cookies + quoted filenames
# ==============================
if COOKIE_FILENAME:
    cookie_param = f'--cookies "{COOKIE_FILENAME}"'
else:
    cookie_param = ""

!yt-dlp {cookie_param} -f bestaudio[ext=m4a] -o audio.m4a "{VIDEO_URL}"
!yt-dlp {cookie_param} -f 'bv*[height=1080][ext=mp4]+ba[ext=m4a]/mp4' -o video.mp4 "{VIDEO_URL}"
!ffmpeg -y -i audio.m4a audio.wav

# ==============================
# 5. Extract Vocals ONLY (Demucs)
# ==============================
!demucs --two-stems=vocals audio.wav

# ==============================
# 6. Merge Vocals with Original Video (replace soundtrack with vocals only)
# ==============================
!ffmpeg -y -i video.mp4 -i separated/htdemucs/audio/vocals.wav -c:v copy -map 0:v:0 -map 1:a:0 -shortest output_video_vocals_only.mp4

# ==============================
# 6b. Remove temporary files after merging (optional, for privacy/space)
# ==============================
import os
files_to_remove = ["audio.m4a", "audio.wav", "video.mp4"]
folders_to_remove = ["separated"]

for fname in files_to_remove:
    try:
        os.remove(fname)
    except Exception:
        pass

for folder in folders_to_remove:
    if os.path.isdir(folder):
        import shutil
        shutil.rmtree(folder, ignore_errors=True)

# ==============================
# 7. Display the video
# ==============================
from IPython.display import Video
Video("output_video_vocals_only.mp4", embed=True, width=1920)  # you can set width as you prefer
