# -*- coding: utf-8 -*-
"""Make Educational Youtube Videos Halal (remove music).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVzFppcTwwIfaPxMehNdiQvhrJ02oWrk
"""

# ==============================
# 1. Setup (Install needed tools)
# ==============================
!pip install yt-dlp ffmpeg-python demucs

# ==============================
# 2. Upload cookies.txt if authentication is required
# ==============================
from google.colab import files
print("Upload your cookies file from browser now (e.g. www.youtube.com_cookies.txt)")
uploaded = files.upload()

# Automatically select the uploaded cookie file
COOKIE_FILENAME = next((x for x in uploaded if x.endswith('.txt')), None)

# ==============================
# 3. Set YouTube Video URL
# ==============================
VIDEO_URL = "https://www.youtube.com/watch?v=YudpU58uYuM"

# ==============================
# 4. Download audio and video using cookies + quoted filenames
# ==============================
if COOKIE_FILENAME:
    # Note: always wrap the cookie filename in quotes for shell commands!
    cookie_param = f'--cookies "{COOKIE_FILENAME}"'
else:
    cookie_param = ""

!yt-dlp {cookie_param} -f bestaudio[ext=m4a] -o audio.m4a "{VIDEO_URL}"
!yt-dlp {cookie_param} -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 -o video.mp4 "{VIDEO_URL}"
!ffmpeg -y -i audio.m4a audio.wav

# ==============================
# 5. Extract Vocals ONLY (Demucs)
# ==============================
!demucs --two-stems=vocals audio.wav

# ==============================
# 6. Merge Vocals with Original Video (replace soundtrack with vocals only)
# ==============================
!ffmpeg -y -i video.mp4 -i separated/htdemucs/audio/vocals.wav -c:v copy -map 0:v:0 -map 1:a:0 -shortest output_video_vocals_only.mp4
# ==============================
# 6b. Remove temporary files after merging (optional, for privacy/space)
# ==============================
import os

files_to_remove = ["audio.m4a","audio.wav","video.mp4"]

# Demucs creates several folders and files; you can also clean those up if you want (optional):
folders_to_remove = ["separated"] # Demucs output folder

for fname in files_to_remove:
    try:
        os.remove(fname)
    except Exception:
        pass  # ignore if file doesn't exist

for folder in folders_to_remove:
    if os.path.isdir(folder):
        import shutil
        shutil.rmtree(folder, ignore_errors=True)


# ==============================
# 7. Display the video
# ==============================
from IPython.display import  Video
Video("output_video_vocals_only.mp4", embed=True, width=1200)